language: node_js
node_js:
  - "iojs"
  - "0.10"
  - "0.11"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/.bin/mocha -R spec -b --check-leaks tests/unit-node
  - node_modules/.bin/karma start tests/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
